#!/usr/bin/env python3
"""
Validate UDMI files
"""

import argparse
import logging as log
import os
import sys
from pathlib import Path

import udmi
from pyfiglet import Figlet

LOGLEVEL = os.environ.get("LOGLEVEL", "DEBUG").upper()

log.basicConfig(stream=sys.stdout, level=LOGLEVEL)


def main(argv=sys.argv[1:]):

    figl = Figlet(font='standard')
    print(figl.renderText('validate UDMI'))

    parser = argparse.ArgumentParser(description="Validate UDMI files.")
    parser.add_argument("input", help="input file")
    parser.add_argument(
        "--type", default="Pointset", help="Payload type (Pointset, MetaData, State, Config, Discovery)"
    )

    args = parser.parse_args(args=argv)

    payload = Path(args.input).read_text()
    payload_type = args.type

    try:
        res = getattr(udmi, payload_type).from_string(payload)
        print(res)
        log.info("Valid payload structure")
        return 0
    except Exception as e:
        log.exception("Malformed payload structure: {0}".format(e))
        return 1

if __name__ == "__main__":
    sys.exit(main())
